// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySlashOp(arg1, arg2) {
  return window['go']['bridge']['App']['ApplySlashOp'](arg1, arg2);
}

export function CycleBlockTodo(arg1) {
  return window['go']['bridge']['App']['CycleBlockTodo'](arg1);
}

export function EnsurePage(arg1) {
  return window['go']['bridge']['App']['EnsurePage'](arg1);
}

export function ExportPageHTML(arg1, arg2) {
  return window['go']['bridge']['App']['ExportPageHTML'](arg1, arg2);
}

export function GetBacklinks(arg1) {
  return window['go']['bridge']['App']['GetBacklinks'](arg1);
}

export function GetPage(arg1) {
  return window['go']['bridge']['App']['GetPage'](arg1);
}

export function GetTheme() {
  return window['go']['bridge']['App']['GetTheme']();
}

export function IndentBlock(arg1) {
  return window['go']['bridge']['App']['IndentBlock'](arg1);
}

export function InsertBlockAfter(arg1, arg2) {
  return window['go']['bridge']['App']['InsertBlockAfter'](arg1, arg2);
}

export function ListPagesByProperty(arg1, arg2) {
  return window['go']['bridge']['App']['ListPagesByProperty'](arg1, arg2);
}

export function ListVaultPages() {
  return window['go']['bridge']['App']['ListVaultPages']();
}

export function NotesRoot() {
  return window['go']['bridge']['App']['NotesRoot']();
}

export function OutdentBlock(arg1) {
  return window['go']['bridge']['App']['OutdentBlock'](arg1);
}

export function QueryBlocks(arg1) {
  return window['go']['bridge']['App']['QueryBlocks'](arg1);
}

export function ResolveWikilink(arg1) {
  return window['go']['bridge']['App']['ResolveWikilink'](arg1);
}

export function SearchBlocks(arg1) {
  return window['go']['bridge']['App']['SearchBlocks'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['bridge']['App']['SetTheme'](arg1);
}

export function Startup(arg1) {
  return window['go']['bridge']['App']['Startup'](arg1);
}

export function UpdateBlock(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateBlock'](arg1, arg2);
}
