// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {domain} from '../models';
import {storage} from '../models';
import {context} from '../models';

export function AIChat(arg1:string,arg2:string):Promise<string>;

export function ApplySlashOp(arg1:string,arg2:string):Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function CycleBlockTodo(arg1:string):Promise<void>;

export function EnsurePage(arg1:string):Promise<void>;

export function ExportPageHTML(arg1:string,arg2:string):Promise<void>;

export function GetAISettings():Promise<bridge.AISettingsDTO>;

export function GetAppVersion():Promise<string>;

export function GetBacklinks(arg1:string):Promise<Array<domain.Block>>;

export function GetLocale():Promise<string>;

export function GetPage(arg1:string):Promise<Array<bridge.PageBlock>>;

export function GetSemanticGraphEdges():Promise<Array<storage.WikiGraphSemanticEdge>>;

export function GetSemanticRelatedForPage(arg1:string,arg2:number):Promise<Array<bridge.SemanticRelatedDTO>>;

export function GetSyncSettings():Promise<bridge.SyncSettingsDTO>;

export function GetTheme():Promise<string>;

export function GetWikiGraph():Promise<storage.WikiGraph>;

export function HealthResetLocalSearchIndex():Promise<void>;

export function IndentBlock(arg1:string):Promise<void>;

export function InsertBlockAfter(arg1:string,arg2:string):Promise<void>;

export function InsertChildBlock(arg1:string,arg2:string):Promise<void>;

export function IsAIReachable():Promise<boolean>;

export function ListLANSyncPeers():Promise<Array<bridge.LANPeerDTO>>;

export function ListPagesByProperty(arg1:string,arg2:string):Promise<Array<string>>;

export function ListVaultFiles():Promise<Array<bridge.VaultFileDTO>>;

export function ListVaultPages():Promise<Array<string>>;

export function MoveBlockUnder(arg1:string,arg2:string):Promise<void>;

export function NotesRoot():Promise<string>;

export function OpenInWave(arg1:string):Promise<bridge.WaveOpenResult>;

export function OpenVaultFile(arg1:string):Promise<void>;

export function OutdentBlock(arg1:string):Promise<void>;

export function PairLANSyncWith(arg1:string,arg2:number,arg3:string):Promise<void>;

export function QueryBlocks(arg1:string):Promise<Array<domain.Block>>;

export function ReorderBlockBefore(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveTerminalCwd(arg1:string):Promise<string>;

export function ResolveWikilink(arg1:string):Promise<string>;

export function RunBlockCommand(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<bridge.TerminalCommandResultDTO>;

export function RunVaultCommand(arg1:string):Promise<bridge.ConsoleCommandResult>;

export function SearchBlocks(arg1:string):Promise<Array<storage.BlockSearchHit>>;

export function SetAISettings(arg1:bridge.AISettingsDTO):Promise<void>;

export function SetHealthRescan(arg1:any):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetSyncSettings(arg1:bridge.SyncSettingsDTO):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartAIInlineStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartLANSyncAdvertise():Promise<string>;

export function StartTerminalSession(arg1:string):Promise<bridge.TerminalSessionDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopLANSyncAdvertise():Promise<void>;

export function SuggestTagsForBlock(arg1:string):Promise<Array<string>>;

export function SyncVaultS3():Promise<void>;

export function SyncVaultWebDAV():Promise<void>;

export function UpdateBlock(arg1:string,arg2:string):Promise<void>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
