// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {domain} from '../models';
import {storage} from '../models';
import {context} from '../models';

export function AIChat(arg1:string,arg2:string):Promise<string>;

export function ApplySlashOp(arg1:string,arg2:string):Promise<void>;

export function CycleBlockTodo(arg1:string):Promise<void>;

export function EnsurePage(arg1:string):Promise<void>;

export function ExportPageHTML(arg1:string,arg2:string):Promise<void>;

export function GetAISettings():Promise<bridge.AISettingsDTO>;

export function GetAppVersion():Promise<string>;

export function GetBacklinks(arg1:string):Promise<Array<domain.Block>>;

export function GetLocale():Promise<string>;

export function GetPage(arg1:string):Promise<Array<bridge.PageBlock>>;

export function GetSemanticGraphEdges():Promise<Array<storage.WikiGraphSemanticEdge>>;

export function GetSemanticRelatedForPage(arg1:string,arg2:number):Promise<Array<bridge.SemanticRelatedDTO>>;

export function GetTheme():Promise<string>;

export function GetWikiGraph():Promise<storage.WikiGraph>;

export function IndentBlock(arg1:string):Promise<void>;

export function InsertBlockAfter(arg1:string,arg2:string):Promise<void>;

export function ListPagesByProperty(arg1:string,arg2:string):Promise<Array<string>>;

export function ListVaultPages():Promise<Array<string>>;

export function NotesRoot():Promise<string>;

export function OutdentBlock(arg1:string):Promise<void>;

export function QueryBlocks(arg1:string):Promise<Array<domain.Block>>;

export function ReorderBlockBefore(arg1:string,arg2:string):Promise<void>;

export function ResolveWikilink(arg1:string):Promise<string>;

export function SearchBlocks(arg1:string):Promise<Array<storage.BlockSearchHit>>;

export function SetAISettings(arg1:bridge.AISettingsDTO):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartAIInlineStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SuggestTagsForBlock(arg1:string):Promise<Array<string>>;

export function UpdateBlock(arg1:string,arg2:string):Promise<void>;
