// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {bridge} from '../models';
import {storage} from '../models';
import {context} from '../models';

export function ApplySlashOp(arg1:string,arg2:string):Promise<void>;

export function CycleBlockTodo(arg1:string):Promise<void>;

export function EnsurePage(arg1:string):Promise<void>;

export function ExportPageHTML(arg1:string,arg2:string):Promise<void>;

export function GetBacklinks(arg1:string):Promise<Array<domain.Block>>;

export function GetAppVersion():Promise<string>;

export function GetLocale():Promise<string>;

export function GetPage(arg1:string):Promise<Array<bridge.PageBlock>>;

export function GetWikiGraph():Promise<storage.WikiGraph>;

export function GetTheme():Promise<string>;

export function IndentBlock(arg1:string):Promise<void>;

export function InsertBlockAfter(arg1:string,arg2:string):Promise<void>;

export function ListPagesByProperty(arg1:string,arg2:string):Promise<Array<string>>;

export function ListVaultPages():Promise<Array<string>>;

export function NotesRoot():Promise<string>;

export function OutdentBlock(arg1:string):Promise<void>;

export function QueryBlocks(arg1:string):Promise<Array<domain.Block>>;

export function ResolveWikilink(arg1:string):Promise<string>;

export function ReorderBlockBefore(arg1:string,arg2:string):Promise<void>;

export function SearchBlocks(arg1:string):Promise<Array<storage.BlockSearchHit>>;

export function SetTheme(arg1:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateBlock(arg1:string,arg2:string):Promise<void>;
